programcalistir:derleme bagla calistir

derleme:
	g++ -c -I "./include/" ./src/Sorted-Unsorted-Array.cpp -o ./lib/Sorted-Unsorted-Array.o
	
bagla:
	g++ ./lib/Sorted-Unsorted-Array.o -o ./bin/Program

calistir:
	./bin/Program 